# ----- ETAPA 1: Constructor (Builder) -----
# Usamos una imagen base para instalar las librerías
FROM python:3.10-slim as builder
WORKDIR /build
COPY requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt


# ----- ETAPA 2: Ejecución (Runtime) -----
FROM python:3.10-slim
WORKDIR /app

COPY --from=builder /root/.local /root/.local
COPY . .
ENV PATH=/root/.local/bin:$PATH
CMD ["python", "script.py"]
